load: [1]
standard_accuracy: [1]

scan_path_model: [ResNet2810]
downstream_model: [ImageNetDeepAugmentAndAugmix]
downstream_model_type: [Classifier]

dataset: [imagenetSubset]
batch_size: [100]

foveation_size: [0.15]
noise_factor: [0]
filter_size: [41]
blur_sigma: [35]

seed: [0]