train: [0]
test: [0]
load: [1]
optimize_foveation_pos: [1]

scan_path_model: [Empty]
downstream_model: [ImageNetDeepAugmentAndAugmix]
downstream_model_type: [Classifier]

dataset: [imagenet]
test_dataset: [mit1003]

batch_size: [10]
lr: [0.1]
epochs: [20]

deblur_steps: [10]
foveation_size: [0.2]
noise_factor: [0.15]
filter_size: [41]
forgetting: [0.8]
blur_sigma: [10]

seed: [0]