train: [0]
test: [0]
plot: [1]
pretrained: [1]
load: [1]
optimize_foveation_pos: [1]
adversarial: [0]

scan_path_model: [Empty]
downstream_model: [DenoisingAutoencoder]
downstream_model_type: [Reconstructer]

dataset: [cifar10]
test_dataset: [imagenetSubset]
batch_size: [32]
lr: [0.1]
epochs: [20]

deblur_steps: [8]
foveation_size: [0.15]
noise_factor: [0]
filter_size: [5]
forgetting: [1]

seed: [0]