test: [1]
#generate_scanpath_adversarial: [1]
trained_scanpath_model: [1]
load: [1]

scan_path_model: [ResNet2810]
downstream_model: [Standard]
downstream_model_test: [CIFAR100_ResNet32]
downstream_model_type: [Classifier]

dataset: [cifar10]
test_dataset: [cifar100Subset]
batch_size: [256]
test_batch_size: [100]
lr: [0.0001]
epochs: [200]

deblur_steps: [8]
foveation_size: [0.15]
noise_factor: [0]
filter_size: [5]
forgetting: [1]

seed: [0]