plot: [1]
optimization: [1]
plot_type: [plot_scanpaths, plot_scanpath_loss]
plot_img_names: [['i1344739819', 'i12030916', 'i12049788', 'i2057541', 'i1508828', 'i105415081', 'i142662322']]

scan_path_model: [Empty]
downstream_model: [DenoisingAutoencoder]
downstream_model_type: [Reconstructer]

dataset: [cifar10]
test_dataset: [mit1003]
batch_size: [256]
lr: [0.1]
epochs: [10]
resize: [256]
crop: [224]

deblur_steps: [10]
foveation_size: [0.15]
noise_factor: [0]
filter_size: [41]
forgetting: [0.9]
blur_sigma: [35]

seed: [0]