train: [0]
pretrained: [1]
trained_scanpath_model: [1]
test: [1]
plot: [0]
load: [1]

scan_path_model: [ResNet2810]
downstream_model: [DenoisingAutoencoder]
downstream_model_type: [Reconstructer]

dataset: [cifar10]
test_dataset: [mit1003]
batch_size: [256]
lr: [0.0001]
epochs: [200]
forgetting_test: [[0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]]

deblur_steps: [8]
foveation_size: [0.15]
noise_factor: [0.1]
filter_size: [5]
forgetting: [0.9]

seed: [0]