train: [0]
test: [0]
pretrained: [1]
plot: [1]
load: [1]
optimize_foveation_pos: [1]

scan_path_model: [Empty]
downstream_model: [DenoisingAutoencoder]
downstream_model_type: [Reconstructer]

dataset: [imagenet]
test_dataset: [mit1003]

batch_size: [5]
lr: [0.1]
epochs: [10]

deblur_steps: [1]
foveation_size: [0.2]
noise_factor: [0.15]
filter_size: [41]
forgetting: [0.8]
blur_sigma: [10]

seed: [0]